- name: deploy vault configuration
  ansible.builtin.template:
    src: vault.hcl.tpl
    dest: /etc/vault.d/vault.hcl

- name: enable and start vault service
  ansible.builtin.service:
    name: vault
    enabled: yes
    state: started
